name: Release Build 

on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }} (with non-required env)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      - name: update apt
        run: sudo apt-get update
      - name: install libuedev
        run: sudo apt-get install -y libudev-dev
      - uses: actions/checkout@master
      - name: Compile and release
        uses: ./.github/actions 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md"
          ARCHIVE_TYPES: ${{ matrix.archive }}
          